
export const styles = {
    container: 'flex justify-between bg-brandDark h-20 w-full text-sm font-semibold leading-5 top-0',
    image: 'w-100 h-auto',
    imageDiv: 'relative',
    imageText: 'text-white font-bold text-xs md:text-lg lg:text-xl absolute top-0 left-0 p-4 lg:right-0 lg:bottom-0 lg:top-auto',
    imageTextButton: 'text-white bg-brand text-xs p-2 m-2 md:text-md lg:text-md rounded-md hover:bg-brandDark hidden lg:block',
    detailContainer: 'absolute bottom-0 left-0 p-4 items-center lg:right-0 lg:left-auto',
    buttonContainer: 'flex text-xs items-center justify-center space-x-4 p-1 bg-white rounded-md shadow-md mb-2',
    // reviewsContainer: 'rounded-md mb-2 lg:mb-6 bg-white border border-grayLight',
    reviewContent: 'flex p-1',
    reviewText: 'flex text-white text-xs md:text-sm justify-center items-center opacity-80 pl-4',
    averageRating: 'flex w-6 h-6 md:w-10 md:h-10 rounded-full bg-brandDarker p-4 justify-center items-center text-white text-xs md:text-md mr-2',
    chatIcon: 'text-gray w-4 h-4 md:w-6 md:h-6 lg:w-8 lg:h-8 ml-2',
    buttonStats: 'bg-transparent border-dashed border border-grayLight p-2 text-white',
    imageDivIcon: 'inline-block vertical-align-middle mr-2 text-brand',
    statIcon: 'md:inline-block md:vertical-align-middle md:mr-2 text-brand w-5 h-5',
    left: 'flex items-center h-full w-full',
    right: 'flex justify-end items-center gap-8 pr-8 h-full w-full',
    button: 'btn bg-brandDark capitalize text-white text-xs md:text-sm lg:text-md hover:opacity-80 hover:bg-brandDark',
    heading: 'text-md',
    message: 'block font-bold text-gray pt-2 pb-2 pl-2',
    buttonGroup: 'absolute right-0 pr-2',
    buttonAction: ' md:bg-brandDark text-white md:pl-4 md:pr-4 pt-2 pb-2 rounded-md text-xs md:text-sm lg:text-md hover:opacity-80 md:hover:bg-brandDarker',
    saveButton: ' md:bg-brandDark text-white md:pl-4 md:pr-4 pt-2 pb-2 text-xs md:text-sm lg:text-md hover:opacity-80 md:hover:bg-brandDarker',
    buttonActionText: 'hidden md:inline',
    reviewsContainer: 'flex lg:mb-4 items-center bg-white rounded-md py-2 px-4',
    starRating: 'flex mr-2',
    ratingNumber: 'font-semibold text-lg mr-1',
    reviewCount: 'text-sm opacity-80',
    starIcon: 'text-yellow-400 w-5 h-5', 
    reviewHeading: 'text-xs md:text-sm font-medium text-brandDarker',
    progress: 'progress progress-info w-full',
    reviewScore: 'text-xs md:text-sm font-medium text-brandDarker ml-3',
    subHeading: 'flex justify-center items-center text-sm md:text-md text-brandDarker',
    reviewRating: 'flex justify-center items-center text-brandDarker text-md md:text-lg font-medium',


} 